### ISSUE TITLE
Cache keys produce filenames of infinite length

### ISSUE THREAD

**Issue by ernoblue** [seddonym/grimp#106]
Hello, 
today's grimp update broke our CI.

Symptom (from import-linter):
```[2023-03-03T12:31:30.316Z] [Errno 36] File name too long: '.grimp_cache/<312 CHARACTERS REMOVED AS IT COULD CONTAIN SENSITIVE DATA>.data.json'```

The problem seems to originate from a `CacheFileNamer.make_data_file_unique_string()` method, line:
```package_names = (p.name for p in found_packages)```

So it will inevitably fail on big-enough codebases.

I guess the solution would be to use some sort of hash from the value generated by this method as a cache key.

**Comment by ernoblue** [comment]
The import linter reports: `Analyzed 1923 files, 4140 dependencies.` Although IMO the most important factor here is the depth of the tree + the length of the filenames there. 

Thank you for the workaround tip. :)

**Comment by ChristianWeymannTNG** [comment]
Hi @seddonym 
As an extra data point: we ran into the same issue in our project using `import-linter` as a pre-commit hook with 10 root packages. The workaround is working for as well, thank you very much.

**Comment by seddonym** [comment]
Great, thanks! Will be fixing in the next release.
