### ISSUE TITLE
What is a Route?

### ISSUE THREAD

**Issue by exterm** [seddonym/grimp#160]
Hi!

I’m working with layer violations and trying to find out whether new ones were added compared to a known state or not. 

Using find_illegal_dependencies_for_layers, I get a collection of Routes back. 

However, I’m not quite sure how to interpret them. 

E.g.,
```
heads = a, b
middle = c
tails = d, e
```

Does that mean that `a -> c -> d`, `a -> c -> e`, `b -> c -> d` and `b -> c -> e` all exist?

It seems that the Route would look the same if one of the chains didn’t exist. What am I missing?

**Comment by exterm** [comment]
I got it - the answer is yes, it implies the existence of all the chains. As indeed removing any chain would remove at least one head or tail.

**Comment by seddonym** [comment]
Great. For future reference, here are the docs on Routes: https://grimp.readthedocs.io/en/stable/usage.html#Route
