### ISSUE TITLE
Better handling of installable packages without __init__.py

### ISSUE THREAD

**Issue by seddonym** [seddonym/grimp#53]
If you have a package that's installed via a setup.py, but it doesn't have an `__init__.py` file at the top level, you get the following error:

```
...
File ".../grimp/adaptors/packagefinder.py", line 23, in determine_package_directory
    assert package_filename.origin  # For type checker.
AssertionError
```
The simple fix at the user's end is to add the missing `__init__.py` file. But it's a confusing error message.

The problem is, it's assuming that the `origin` attribute on the returned ModuleSpec will always be set. That's not true, see the docs: https://docs.python.org/3.6/library/importlib.html#importlib.machinery.ModuleSpec.origin

**Comment by bafulton** [comment]
I just ran into this myself, and I can't add the missing `__init__.py`, as it's a large, multi-user corporate project and it breaks other imports.

**Comment by seddonym** [comment]
Sorry this is causing you pain! I will try to get onto it at some point.

**Comment by seddonym** [comment]
Hi Ben - I've looked into this a bit more and have realised that strictly speaking a project without an `__init__.py` is a namespace package. These are valid Python and it would take a bit of work to formally support these, so for the moment the way I'm addressing this is just to raise a more helpful exception.

I'm going to close this issue, but I've open [a new (low priority) PR](https://github.com/seddonym/grimp/issues/80) to support namespace packages.

If you just want to use import-linter locally you could consider adding the `__init__.py` to your `.gitignore`.

Sorry I can't be of more help in your specific case!
