### ISSUE TITLE
Feature: Add a use-case to handle multiple projects at run-time.

### ISSUE THREAD

**Issue by Incognito** [seddonym/grimp#84]
I've been working with grimp to experiment with mapping project dependencies and structures over multiple projects at run-time, including previous versions of a project to watch changes in dependencies over time.

I have a fork that lets me do this but if there is interest in the broader collection of people using grimp it might be useful to make it a proper part of the project. This issue is mostly here to anchor any interest in a feature like that and discuss if anyone else wants to use that kind of feature.

**Comment by seddonym** [comment]
Thanks for this @Incognito, from what I remember this was an outcome of a conversation we had.

I'm not sure how actionable this is in its current form, and as there hasn't been any activity on the ticket for a while, I'm going to close it. Happy to reopen if we can understand better what is needed.
