### ISSUE TITLE
Feature request: Expose cycles as part of the public API

### ISSUE THREAD

**Issue by Incognito** [seddonym/grimp#85]
Presently I would like to detect dependency cycles in my graphs which requires either access to private use of networkx

```
from typing import Iterator, List

import networkx
from grimp.adaptors.graph import ImportGraph


def dependency_cycles(graph: ImportGraph) -> Iterator[List[str]]:
    # Violates private internals of grimp by accessing private implementation
    cycles = networkx.simple_cycles(graph._networkx_graph)

    for cycle in cycles:
        if len(cycle) > 1:
            yield cycle
```

Alternatively I would need to re-implement topsort on-top of walking through grimp.

Benefits: Less redundant code, less violations of internals.
Drawbacks: Your project adds a new algo/feature to the public API.

**Comment by Incognito** [comment]
For what it's worth, I've added this feature in a new package  https://github.com/Incognito/python-architecture-linter/tree/main/grimp_package_metrics . I'm not sure if I want to maintain it long-term but the code does the job and is minimal enough that anyone can just cut+paste it into their project if they want to avoid an external dependency on it.

**Comment by seddonym** [comment]
I like this idea.

It does make me think, though, that maybe it would be better just to expose the networkx graph as a public attribute (i.e., remove the `_` prefix). That way Grimp could give more formal support to many use cases, not just this one. Thoughts?

**Comment by Incognito** [comment]
I guess there's a few common option to consider when looking at this:

1. Just forward the object in the public API. Kind of a "law of demeter" violation or information hiding. Exposes the internals directly to the public API so you'd have a hard time doing new releases because the scope of your API inherits all of it. If you went for it I'd suggest just keeping networkx private so it is clear it might be broken in any `1.1.n+1` release (assuming you like semver). Making it public
2. Polymorphic union of grimp and networkx. I don't like this one beucase I think grimp provides a nice layer that behaves as a sort-of hypergraph abstraction on-top of the direct import graph, perhaps you can find nice semantics to "extend" it but I see that as making a duck with wheels.
3. Add the feature directly with a new method. A bit annoying because you need to do a new release for each feature.
4. Add a variation-point that lets you add features outside of the core project. Offer a "plugins" interface in the public API which can then negotiate on a common version of networkx but still hide details behind grimp's public API and the api of the "extension package", it would mean each get versioned and released separately and you would scale out new "non-core features" this way. It could let projects have a cleaner way to get in-between the bones of grimp in their project spaces.
5. Decouple graph algos from the graph itself, letting you port a graph between different algo providers, which frees you from the original constraint of a hard dependency on networkx. It also helps unlock some feature roadmap items in the shape of "I want to save graphs as text so I can load it later".

I'd probably lean towards 3, 5, and 4 in that order (assuming the the constraint of `time/reward` is what you are optimising for). I'd suggest not doing options 1 or 2 as it inflates your public API and long term maintenance effort (and bug reports that are coming from upstream).

**Comment by seddonym** [comment]
Thanks for these thoughts and sorry it's taken me a while to digest them.

I think you're right that there would be a downside to more closely coupling to networkx. Currently we're at option 5. Grimp's architecture currently makes it easy to swap in a different implementation of the graph. [Here is the abstraction](https://github.com/seddonym/grimp/blob/00a139190aa68da152b9177c79986a96bce401fa/src/grimp/application/ports/graph.py#L5) (which doesn't depend on networkx) which is then [plugged in the main module](https://github.com/seddonym/grimp/blob/00a139190aa68da152b9177c79986a96bce401fa/src/grimp/main.py#L16) (you could call this the 'composition root').

Although we haven't got much value out of this decoupling yet, I do think it's possible that we'll want to write our own shortest path algorithm which is better at dealing with groups of paths (and which networkx doesn't support). Or we might even want to swap in a Cython-backed graph to increase Grimp's speed. So perhaps it's worth designing with the idea of swappable backends in mind.

With that in mind, I think a nice compromise might be to add a new public function which converts the Grimp graph object into a networkx graph. That would allow Grimp's core graph to have a different backend if need be in the future. The API could be something like:

```
import grimp
>>> graph = grimp.build_graph('somepackage')
>>> graph
<ImportGraph: 'somepackage', 'somepackage.foo', 'somepackage.bar'>
>>> grimp.to_networkx_graph(graph)
<networkx.classes.digraph.DiGraph at 0x1309e5c40>
```

What do you think?

**Comment by seddonym** [comment]
The latest version of Grimp (2.0) no longer uses NetworkX, instead it recommends building a NetworkX graph from the Grimp graph if you need to do analysis using an unsupported algorithm. https://grimp.readthedocs.io/en/stable/networkx.html

I think this is the direction we're going to go for the time being, hope it makes sense.

**Comment by Incognito** [comment]
That's a really cool approach, thanks!
