### ISSUE TITLE
Improve handling of subpackages passed to `build_graph`

### ISSUE THREAD

**Issue by seddonym** [seddonym/grimp#88]
`build_graph` was built with the intention of passing top level packages only. It does (unintentionally) accept subpackages - but the behaviour is not coherent.

We should decide whether to formally support this, and if so how it should behave.
  
In the current version of Grimp, compare building the graph using the root, and doing the same with a subpackage. Here's the root first:
```
>>> graph = grimp.build_graph("django")
>>> graph.find_modules_directly_imported_by("django.db.models.base")
{'django.db.models.deletion', 'django.db', 'django.utils.encoding', 'django.core.exceptions', 'django.utils.hashable', 'django.db.models.signals', 'django.db.models.constants', 'django.db.models.utils', 'django', 'django.core.checks', 'django.db.models.fields.related', 'django.db.models.constraints', 'django.conf', 'django.db.models', 'django.db.models.functions', 'django.db.transaction', 'django.utils.text', 'django.db.models.manager', 'django.db.models.options', 'django.db.models.query', 'django.utils.translation', 'django.apps'}
```
All well and good. This time we build using a subpackage. Note we use include_external_packages so that we can see any imports happening outside that subpackage that are still in Django:

```
>>> graph = grimp.build_graph("django.db", include_external_packages=True)
```

The first undesirable behaviour is that with the modules in the graph are not under the django namespace but rather the subpackage's namespace:

```
>>> sorted(graph.modules)[20:25]
['db.backends.base.introspection', 'db.backends.base.operations', 'db.backends.base.schema', 'db.backends.base.validation', 'db.backends.ddl_references']
```
Secondly (because of this) the imports don't correctly map on to the models:

```
>>> graph.find_modules_directly_imported_by("db.models.base")
{'django', 'functools', 'copy', 'warnings', 'inspect', 'itertools'}
```
This should be including the imports within `django.db`, such as `django.db.models.deletion`.

# Course of action

I think the best thing should probably be to raise an exception if a subpackage (i.e. anything with a `.`) is passed to `build_graph`. Although this means users will be forced to build a larger graph than they may need (if they're only interested in a subpackage), it keeps the API simple, which I think is more important.

Open to other opinions...

**Comment by ZipFile** [comment]
Can't we force user (raise an exception) to build a larger graph only when subpackage is not self-contained (contains imports outside of the subtree) or not explicitly included in `build_graph` call? This way we'll be able to support good chunk of namespace packages (e.g. `google.protobuf`) and some other monorepo-ish style of packages (e.g. `myproj.core` with common code for microservices `myproj.svc1` and `myproj.svc2` without any other `myproj` deps). It feels unintuitive to forbid analyzing just any subpackages, because some of them behave like a regular package, but happens to be within a namespace.

**Comment by seddonym** [comment]
With the newly added support for namespaced packages, the behaviour is now coherent: if you pass a non-portion subpackage to build_graph then it will raise grimp.exceptions.NotATopLevelModule.
