### ISSUE TITLE
Annotate ImportGraph.get_import_details with a TypedDict

### ISSUE THREAD

**Issue by seddonym** [seddonym/grimp#94]
It would be great to improve the type annotations on [get_import_details](https://grimp.readthedocs.io/en/stable/usage.html#ImportGraph.get_import_details) by using a [TypedDict](https://peps.python.org/pep-0589/#class-based-syntax).

This will help downstream packages such as Import Linter better work with the results of that method.

Note: TypedDict is only available in `typing` from Python 3.8, so for the time being we'll need to import it from `typing_extensions`.

**Comment by yakMM** [comment]
Any reason for not using a dataclass as return type?

```py
@dataclass
class ImportDetail:
    importer: str
    imported: str
    line_number: int
    line_contents: str

def get_import_details(...) -> list[ImportDetail]: ...
```

**Comment by seddonym** [comment]
The reason I chose to use native Python objects rather than dataclasses in the external API was to reduce the number of imports / dependencies needed by clients. I love dataclasses but IMO it's nicer to favour native data types at the boundaries, where practical.

Aside from that, if we were to change this now it would be backwards incompatible. Makes sense?

**Comment by yakMM** [comment]
Yes I get the backward compatibility argument.

As for dataclass in general, they are part of native python in my mind, but I assume the project was supporting versions older than python 3.7, then it makes sense.
